---
title: "Data Sciece Homework 5"
author: "Szutor Bálint & Jászai Tamás"
date: '2019.11.27'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
suppressMessages(library(data.table))
suppressMessages(library(broom))
suppressMessages(library(purrr))
suppressMessages(library(caret))
suppressMessages(library(magrittr))
suppressMessages(library(MLmetrics))

# Valamiért nem engedi az adatot pusholni a git
data <- fread("C:/Users/Ildiko/OneDrive/Projekt/LeaugeDataMege.csv")
```


```{r}

# Megpróbáljuk a sebzést előrejelezni például az aranyuk, killjei és hasonlóik függvényében.
  
formula1<-as.formula(totalDamageDealt~goldEarned+I(goldEarned^2))
formula2<-as.formula(totalDamageDealt~goldEarned+I(goldEarned^2)+assists + kills)
formula3<-as.formula(totalDamageDealt~goldEarned+goldEarned+I(goldEarned^2) + Mast)
formula4<-as.formula(totalDamageDealt~goldEarned + Mast+ kills + assists)
```


### Train vs. test error
```{r}

# Az órai anyag alapján

train_proportion<-0.7
train_index<-sample(1:nrow(data),floor(nrow(data)*train_proportion))
data_train<-data[train_index,]
data_test<-data[-train_index,]
model1<-lm(formula1,data = data_train)
model2<-lm(formula2,data = data_train)
model3<-lm(formula3,data = data_train)
model4<-lm(formula4,data = data_train)
data_train<-data_train[,Model1:=predict(model1,newdata = data_train)] %>% .[,Model2:=predict(model2,newdata = data_train)] %>% .[,Model3:=predict(model3,newdata = data_train)] %>% .[,Model4:=predict(model4,newdata=data_train)]
mse_train1<-MSE(data_train[,totalDamageDealt],data_train[,Model1])
mse_train2<-MSE(data_train[,totalDamageDealt],data_train[,Model2])
mse_train3<-MSE(data_train[,totalDamageDealt],data_train[,Model3])
mse_train4<-MSE(data_train[,totalDamageDealt],data_train[,Model4])
rounded_mse_train<-round(c(mse_train1,mse_train2,mse_train3,mse_train4),digits = 2)
data_test<-data_test[,Model1:=predict(model1,newdata = data_test)] %>% .[,Model2:=predict(model2,newdata = data_test)] %>% .[,Model3:=predict(model3,newdata = data_test)] %>% .[,Model4:=predict(model4,newdata=data_test)]
mse_test1<-MSE(data_test[,totalDamageDealt],data_test[,Model1])
mse_test2<-MSE(data_test[,totalDamageDealt],data_test[,Model2])
mse_test3<-MSE(data_test[,totalDamageDealt],data_test[,Model3])
mse_test4<-MSE(data_test[,totalDamageDealt],data_test[,Model4])
rounded_mse_test<-round(c(mse_test1,mse_test2,mse_test3,mse_test4),digits = 2)
cbind(c("model1","model2","model3","model4"),"train MSE"=rounded_mse_train,"test MSE"=rounded_mse_test)
```


### K-fold cross validation

```{r}

# Package függvényeit használva

train_control<-trainControl(method="cv",number=5)
set.seed(2)
model1cv<-train(formula1,data=data,trControl=train_control, method="lm")
model2cv<-train(formula2,data=data,trControl=train_control, method="lm")
model3cv<-train(formula3,data=data,trControl=train_control, method="lm")
model4cv<-train(formula4,data=data,trControl=train_control, method="lm")
a<-model1cv$results$RMSE
b<-model2cv$results$RMSE
c<-model3cv$results$RMSE
d<-model4cv$results$RMSE
rounded_mse_cv<-round(c(a,b,c,d),digits = 2)
cbind(c("model1","model2","model3","model4"),"CV MSE" = rounded_mse_cv)
```


```{r}
cbind(c("model1","model2","model3","model4"),"train MSE"=rounded_mse_train,"test MSE"=rounded_mse_test,"CV MSE" = rounded_mse_cv)

# Tehát a második modellt fogjuk használni.
```